varnish:
  image: million12/varnish
  links:
    - web-app:backend-host
  volumes:
    - ./varnish-config:/etc/varnish
  ports:
    - "8081:80"
web-app:
  build: .
  restart: always
  command: python /app/app.py
  volumes:
    - ./flask:/app
  ports:
    - "5000:5000"
